apis/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from apis import views

app_name = 'api'
urlpatterns = [
    # authentication api
    path('api-token-auth/', views.CustomObtainAuthToken.as_view(), name='api_token_auth'),
    path('api-token-logout/', views.Logout.as_view(), name='api_token_logout'),

    path('password/', views.Password.as_view(), name='forgot-password'),
    path('reset/', views.Reset.as_view(), name='reset-password'),
    path('request/', views.Request.as_view(), name='request'),

    # community api
    path('fake-post/', views.FakePost.as_view(), name='fake-post'),
    path('fake-comment/', views.FakeComment.as_view(), name='fake-comment'),
    path('posts/', views.PostList.as_view(), name='post-list'),
    path('posts/<int:pk>/', views.PostDetail.as_view(), name='single-post'),
    path('comments/', views.CommentList.as_view(), name='comment-list'),
    path('comments/<int:pk>/', views.CommentDetail.as_view(), name='single-comment'),

    # affiliates api
    path('profile/', views.Profile.as_view(), name='profile'),
    path('list/campaign/', views.ListCampaign.as_view(), name='list-campaign'),
    path('campaigns/', views.CampaignList.as_view(), name='campaign-list'),
    path('campaigns/<int:pk>/', views.CampaignDetail.as_view(), name='single-campaign'),
    path('reports/', views.ReportList.as_view(), name='report-list'),
    path('adashboard/', views.AffiliatesDashboard.as_view(), name='affiliates-dashboard'),
    path('contact/', views.Contact.as_view(), name='contact'),

    # screen recoder api
    path('trade-list/', views.TradeList.as_view(), name='trade-list'),
    path('trade-token/', views.TradeToken.as_view(), name='trade-token'),
    path('srecorder-upload/', views.SRecorderUpload.as_view(), name='srecorder-upload'),
]

cadmin/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'cadmin'
urlpatterns = [
    path('pages/', views.Pages.as_view(), name='pages'),

    path('', views.IndexView.as_view(), name='index'),
    path('index/', views.IndexView.as_view()),
    path('add-user/', views.AddUserView.as_view(), name='add-user'),
    path('users/', views.UsersView.as_view(), name='users'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('recover/', views.RecoverView.as_view(), name='recover'),
    path('set-pw/', views.SetPWView.as_view(), name='set-pw'),
    path('revenue/', views.RevenueView.as_view(), name='revenue'),
    path('revenue-details/', views.RevenueDetailsView.as_view(), name='revenue-details'),
    path('rev-stats/', views.RevStatsView.as_view(), name='stats'),
    path('offers/', views.OffersView.as_view(), name='offers'),
    path('offer-details/', views.OfferDetailsView.as_view(), name='offer-details'),
    path('trades/', views.TradesView.as_view(), name='trades'),
    path('trade-details/', views.TradeDetailsView.as_view(), name='trade-details'),
    path('customers/', views.CustomersView.as_view(), name='customers'),
    path('customer-details/', views.CustomerDetailsView.as_view(), name='customer-details'),
    path('customer-suspend/', views.CustomerSuspend.as_view(), name='customer-suspend'),
    path('transactions/', views.TransactionsView.as_view(), name='transactions'),
    path('transaction-details/', views.TransactionDetailsView.as_view(), name='transaction-details'),
    path('escrows/', views.EscrowsView.as_view(), name='escrows'),
    path('escrow-details/', views.EscrowDetailsView.as_view(), name='escrow-details'),
    path('escrow-release/', views.EscrowRelease.as_view(), name='escrow-release'),
    path('escrow-cancel/', views.EscrowCancel.as_view(), name='escrow-cancel'),
    path('support-center/', views.SupportCenterView.as_view(), name='support-center'),
    path('ticket-details-dispute/', views.TicketDetailsDisputeView.as_view(), name='ticket-details-dispute'),
    path('ticket-details-no-dispute/', views.TicketDetailsNoDisputeView.as_view(), name='ticket-details-no-dispute'),
    path('ticket-priority-change/', views.TicketPriorityChange.as_view(), name='ticket-priority-change'),
    path('id-verify-app/', views.IdVerifyAppView.as_view(), name='id-verify-app'),
    path('id-verify-app-details/', views.IdVerifyAppDetailsView.as_view(), name='id-verify-app-details'),
    path('id-verify-app-accept/', views.IdVerifyAppAccept.as_view(), name='id-verify-app-accept'),
    path('id-verify-app-reject/', views.IdVerifyAppReject.as_view(), name='id-verify-app-reject'),
    path('contact-form/', views.ContactFormView.as_view(), name='contact-form'),
    path('contact-form-details/', views.ContactFormDetailsView.as_view(), name='contact-form-details'),
    path('additional-pages/', views.AdditionalPagesView.as_view(), name='additional-pages'),
    path('additional-page-preview/', views.AdditionalPagePreviewView.as_view(), name='addtional-page-preview'),
    path('additional-pages/move-to-trash-page/', views.MoveToTrashPage.as_view(), name='addpaeg-move-to-trash-page'),
    path('add-new-page/', views.AddNewPageView.as_view(), name='add-new-page'),
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('post-preview/', views.PostPreviewView.as_view(), name='post-preview'),
    path('add-new-post/', views.AddNewPostView.as_view(), name='add-new-post'),
    path('blog/move-to-trash-page/', views.BlogMoveToTrashPage.as_view(), name='blog-move-to-trash-page'),
    path('tags/', views.TagsView.as_view(), name='tags'),
    path('media-library/', views.MediaLibraryView.as_view(), name='media-library'),
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('last-login/', views.LastLoginView.as_view(), name='last-login'),
    path('flagged-posts/', views.FlaggedPostsView.as_view(), name='flagged-posts'),
    path('flagged-post-details/', views.FlaggedPostDetailsView.as_view(), name='flagged-post-details'),
    path('add-landing-page/', views.AddLandingPageView.as_view(), name='add-landing-page'),
    path('add-pers-link/', views.AddPersLinkView.as_view(), name='add-pers-link'),
    path('add-redirection-link/', views.AddRedirectionLinkView.as_view(), name='add-redirection-link'),
    path('documentations/', views.DocumentationsView.as_view(), name='documentations'),
    path('post-issue/', views.PostIssueView.as_view(), name='post-issue'),
    path('seo/', views.SeoView.as_view(), name='seo'),
    path('security-status/', views.SecurityStatusView.as_view(), name='security-status'),
    path('options/', views.OptionsView.as_view(), name='options'),
    path('options-router-blog/', views.OptionsRouterBlogView.as_view(), name='options'),
    path('options-router-forgot-password/', views.OptionsRouterForgotPasswordView.as_view(), name='options'),
    path('campaigns/', views.CampaignsView.as_view(), name='campaigns'),
    path('campaign-updated/', views.CampaignUpdatedView.as_view(), name='campaign-updated'),
    path('affiliates/', views.AffiliatesView.as_view(), name='affiliates'),
    path('add-new-affiliate/', views.AddNewAffiliateView.as_view(), name='add-new-affiliate'),
    path('reports/', views.ReportsView.as_view(), name='reports'),
    path('community-posts/', views.CommunityPostsView.as_view(), name='community-posts'),
    path('community-post-details/', views.CommunityPostDetailsView.as_view(), name='community-post-details'),
    path('community-post-rules/', views.CommunityPostRulesView.as_view(), name='community-post-rules'),
]

raplev/urls.py
from django.urls import path, include
from django.contrib import admin
from cadmin import views as cadmin_views
from django.views.generic import RedirectView

urlpatterns = [
    path('cadmin/', include('cadmin.urls')),
    path('super-admin/', cadmin_views.super_admin_view),
    path('super-admin/', admin.site.urls),
    path('', include('theme.urls')),
    path('api/', include('apis.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('<slug:link>/', cadmin_views.go_page),
]

from django.conf import settings
# if settings.DEBUG:
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crypto/models.py
from django.db import models
# from django.core.mail import send_mail
# import random
# import string
# import timeago
# from datetime import datetime, timezone
# from raplev import settings
# from django.db.models import Q, Sum, Count, F
# from bs4 import BeautifulSoup as bs


class MyModelBase( models.base.ModelBase ):
    def __new__( cls, name, bases, attrs, **kwargs ):
        if name != "MyModel":
            class MetaB:
                db_table = "p127_" + name.lower()

            attrs["Meta"] = MetaB

        r = super().__new__( cls, name, bases, attrs, **kwargs )
        return r

class MyModel( models.Model, metaclass = MyModelBase ):
    class Meta:
        abstract = True


class BTC(MyModel):
    id = models.CharField(max_length=255, unique=True, primary_key=True)
    customer = models.ForeignKey('cadmin.Customers', on_delete=models.CASCADE)
    addr = models.CharField(max_length=255, unique=True)
    label = models.CharField(max_length=255, null=True)
    password = models.CharField(max_length=255, null=True)
    addrs = models.TextField(null=True)
    status = models.CharField(max_length=255, default='main')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.addr


class ETH(MyModel):
    id = models.CharField(max_length=255, unique=True, primary_key=True)
    customer = models.ForeignKey('cadmin.Customers', on_delete=models.CASCADE)
    addr = models.CharField(max_length=255, unique=True)
    label = models.CharField(max_length=255, null=True)
    prv_key = models.CharField(max_length=255, null=True)
    addrs = models.TextField(null=True)
    password = models.CharField(max_length=255, null=True)
    status = models.CharField(max_length=255, default='main')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.addr


class XRP(MyModel):
    id = models.CharField(max_length=255, unique=True, primary_key=True)
    customer = models.ForeignKey('cadmin.Customers', on_delete=models.CASCADE)
    addr = models.CharField(max_length=255, unique=True)
    label = models.CharField(max_length=255, null=True)
    addrs = models.TextField(null=True)
    password = models.CharField(max_length=255, null=True)
    status = models.CharField(max_length=255, default='main')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.addr

cadmin/templates/cadmin/contact-form.html
{% extends 'cadmin/base-site.html' %}
{% load i18n %}
{% load static %}

{% block title %}Contact Form{% endblock %}

{% block page-inner %}
<main class="page__inner js-nav-close-trigger">
    <section class="section">
        <header class="section__header">
            <h1 class="section__heading">Contact Form</h1>
            <form class="section__search form-group search" action="" method="GET">
                <div class="form-group__field-group"><input class="form-group__field" name="search" placeholder="Search in Contacts" value="{{ search }}"><button class="search__btn" type="submit">Search</button></div>
            </form>
        </header>
        <div class="section__inner">
            <table class="section__table table">
                <thead>
                    <tr>
                        <th>Email address</th>
                        <th>Subject</th>
                        <th>Message</th>
                        <th>IP Address</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td><span class="table__mobile-heading">Email address</span><span>{{ item.email_address }}</span></td>
                        <td><span class="table__mobile-heading">Subject</span><span>{{ item.subject }}</span></td>
                        <td><span class="table__mobile-heading">Message</span><span>{{ item.content }}</span></td>
                        <td><span class="table__mobile-heading">IP Address</span><span>{{ item.ip_address }}</span></td>
                        <td><span class="table__mobile-heading">Actions</span><a href="{{ cadmin_url }}/contact-form-details?item_id={{ item.id }}">Details</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <nav class="section__pagination pagination">
                <ul class="pagination__list">
                    {% if items.has_previous %}
                    <li class="pagination__item"><a href="{{ base_url }}page={{ items.previous_page_number }}" rel="first">Prev</a></li>
                    {% else %}
                    <li class="pagination__item disabled">Prev</li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                         {% if items.number == i %}
                         <li class="pagination__item is-active"><a href="{{ base_url }}page={{ i }}">{{ i }}</a></li>
                         {% else %}
                         <li class="pagination__item"><a href="{{ base_url }}page={{ i }}">{{ i }}</a></li>
                         {% endif %}
                    {% endfor %}
                    {% if items.has_next %}
                    <li class="pagination__item"><a href="{{ base_url }}page={{ items.next_page_number }}" rel="next">Next</a></li>
                    {% else %}
                    <li class="pagination__item disabled">Next</li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </section>
</main>
{% endblock %}

cadmin/templates/cadmin/id-verify-app.html
{% extends 'cadmin/base-site.html' %}
{% load i18n %}
{% load static %}

{% block title %}ID Verify Application{% endblock %}

{% block page-inner %}
<main class="page__inner js-nav-close-trigger">
    <section class="section">
        <header class="section__header">
            <h1 class="section__heading">ID Verify Application</h1>
            <form class="section__search form-group search" action="" method="GET">
                <div class="form-group__field-group"><input class="form-group__field" name="search" placeholder="Search in Id verifications" value="{{ search }}"><button class="search__btn" type="submit">Search</button></div>
            </form>
        </header>
        <div class="section__inner">
            <table class="section__table table">
                <thead>
                    <tr>
                        <th>Application ID</th>
                        <th>Username</th>
                        <th>Document type</th>
                        <th>Document</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for item in items %}
                    <tr>
                        <td><span class="table__mobile-heading">Application ID</span><span>{{ item.id }}</span></td>
                        <td><span class="table__mobile-heading">Username</span><a href="#">{{ item.user }}</a></td>
                        <td><span class="table__mobile-heading">Document type</span><span>{{ item.card_name }}</span></td>
                        <td><span class="table__mobile-heading">Document</span><a href="#">{{ item.images_list|join:', ' }}</a></td>
                        <td><span class="table__mobile-heading">Status</span><span>{{ item.get_status_display }}</span></td>
                        <td><span class="table__mobile-heading">Actions</span><a href="{{ cadmin_url }}/id-verify-app-details?item_id={{ item.id }}">Details</a></td>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <nav class="section__pagination pagination">
                <ul class="pagination__list">
                    {% if items.has_previous %}
                    <li class="pagination__item"><a href="{{ base_url }}page={{ items.previous_page_number }}" rel="first">Prev</a></li>
                    {% else %}
                    <li class="pagination__item disabled">Prev</li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                         {% if items.number == i %}
                         <li class="pagination__item is-active"><a href="{{ base_url }}page={{ i }}">{{ i }}</a></li>
                         {% else %}
                         <li class="pagination__item"><a href="{{ base_url }}page={{ i }}">{{ i }}</a></li>
                         {% endif %}
                    {% endfor %}
                    {% if items.has_next %}
                    <li class="pagination__item"><a href="{{ base_url }}page={{ items.next_page_number }}" rel="next">Next</a></li>
                    {% else %}
                    <li class="pagination__item disabled">Next</li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </section>
</main>
{% endblock %}

cadmin/templates/cadmin/ticket-details-dispute.html
{% extends 'cadmin/base-site.html' %}
{% load i18n %}
{% load static %}

{% block title %}Ticket Details Dispute{% endblock %}

{% block page-inner %}
<main class="page__inner js-nav-close-trigger details">
    <section class="details__section section">
        <header class="section__header">
            <h1 class="section__heading"><a class="details__heading-text" href="{{ cadmin_url }}/support-center">Ticket details</a><span> / </span><span>{{ item.id }}</span></h1>
        </header>
        <div class="section__inner data-panel">
            <dl class="data-panel__list">
                <div class="data-panel__item"><dt class="data-panel__heading">Raised by</dt>
                    <dd class="data-panel__value"><a href="#">{{ item.created_by }}</a></dd>
                </div>
                <div class="data-panel__item"><dt class="data-panel__heading">Raised against</dt>
                    <dd class="data-panel__value"><a href="#">{{ item.created_by }}</a></dd>
                </div>
                <div class="data-panel__item"><dt class="data-panel__heading">Trade ID</dt>
                    <dd class="data-panel__value"><a href="{{ cadmin_url }}/trade-details?item_id={{ item.trade.id }}">{{ item.trade.id }}</a></dd>
                </div>
            </dl>
            <dl class="data-panel__list">
                <div class="data-panel__item"><dt class="data-panel__heading">Status</dt>
                    <dd class="data-panel__value">{{ item.trade.get_status_display }}</dd>
                </div>
                <div class="data-panel__item"><dt class="data-panel__heading">Referred to dispute</dt>
                    <dd class="data-panel__value">{{ item.get_is_dispute_display }}</dd>
                </div>
            </dl>
        </div>
    </section>
    <section class="section messages">
        <div class="messages__wrapper">
            {% for mes in item.messages_list %}
            <article class="messages__item message message--{% if mes.writer == item.transaction.trade_initiator %}by{% else %}against{% endif %}">
                <div class="message__user">
                    <div class="message__user-default-icon">
                        <svg class="message__user-icon" width="30">
                            <use xlink:href="{% static 'cadmin/images/icons.svg' %}#user"></use>
                        </svg>
                    </div>
                </div>
                <div class="message__content">
                    <header class="message__header">
                        <h2 class="message__heading">{{ mes.writer }}</h2>
                        <time class="message__data" datetime="2019-10-03 12:23">Sent on {{ mes.created_at }}</time>
                    </header>
                    <div class="message__text">{{ mes.content|safe }}</div>
                </div>
            </article>
            {% endfor %}
        </div>
        <form class="messages__input" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ item.id }}" />
            <textarea class="messages__input-textarea js-expanding-textarea" name="content"  rows="1" placeholder="Enter your message here" required></textarea>
            <div class="messages__input-buttons">
                <label class="messages__input-attach">
                    <input type="file" name="attach_file"  hidden>
                    <svg class="messages__input-icon" width="30">
                        <use xlink:href="{% static 'cadmin/images/icons.svg' %}#paperclip"></use>
                    </svg>
                </label>
                <button class="messages__input-send" type="submit">Send</button>
            </div>
        </form>
    </section>
</main>
{% endblock %}

cadmin/templates/cadmin/trade-details.html
{% extends 'cadmin/base-site.html' %}
{% load i18n %}
{% load static %}

{% block title %}Trade details{% endblock %}

{% block page-inner %}
<main class="page__inner js-nav-close-trigger details trade-details">
    <section class="details__section section">
        <header class="section__header">
            <h1 class="section__heading"><a class="details__heading-text" href="{{ cadmin_url }}/trades">Trade ID</a><span> / </span><span>{{ item.id }}</span></h1>
        </header>
        <div class="section__inner data-panel">
            <dl class="data-panel__list">
                <div class="data-panel__item"><dt class="data-panel__heading">Created at</dt>
                    <dd class="data-panel__value">{{ item.created_at }}</dd>
                </div>
                <div class="data-panel__item"><dt class="data-panel__heading">Offer ID</dt>
                    <dd class="data-panel__value"> <a href="{{ cadmin_url }}/offer-details?item_id={{ item.offer.id }}">{{ item.offer.id }}</a></dd>
                </div>
                <div class="data-panel__item"><dt class="data-panel__heading">Trade initiator</dt>
                    <dd class="data-panel__value"> <a href="#">{{ item.trade_initiator }}</a></dd>
                </div>
            </dl>
            <dl class="data-panel__list">
                <div class="data-panel__item"><dt class="data-panel__heading">Vendor</dt>
                    <dd class="data-panel__value"><a href="#">{{ item.vendor }}</a></dd>
                </div>
                <div class="data-panel__item"><dt class="data-panel__heading">Payment method</dt>
                    <dd class="data-panel__value">{{ item.get_payment_method_display }}</dd>
                </div>
                <div class="data-panel__item"><dt class="data-panel__heading">Amount</dt>
                    <dd class="data-panel__value">{{ item.amount }} {{ item.offer.what_crypto }}</dd>
                </div>
            </dl>
            <dl class="data-panel__list">
                <div class="data-panel__item"><dt class="data-panel__heading">Status</dt>
                    <dd class="data-panel__value">{{ item.get_status_display }}</dd>
                </div>
            </dl>
        </div>
    </section>
    <section class="section section--small">
        <header class="section__header">
            <h2 class="section__heading">Proof</h2>
        </header>
        <div class="section__inner">
            <div class="trade-details__document">
                <!-- <div class="trade-details__file file"><svg class="trade-details__file-icon" width="30">
                        <use xlink:href="{% static 'cadmin/images/icons.svg' %}' %}#play-circle"></use>
                    </svg>
                </div> -->
                {% for doc in item.proof_documents_list %}
                    <img class="proof-transaction__document-img" height="250" src="{{ doc.file.url }}" alt="">
                {% endfor %}
                <div class="trade-details__data">
                    <h3 class="trade-details__heading">Uploaded documents</h3><a class="trade-details__file-name" href="#"> </a>
                    <div class="trade-details__code">
                        <h4 class="trade-details__code-heading">Code</h4>
                        <div class="trade-details__code-field form-group is-not-opened">
                            <div class="form-group__field-group"><input class="form-group__field" {% if item.proof_opened %}type="password"{% else %}type="text"{% endif %} value="{{ item.proof_gift_code|default_if_none:'' }}" disabled></div>
                        </div><span class="trade-details__code-caption">{% if item.proof_opened %}Opened by Vendor{% else %}Not opened by Vendor{% endif %}</span>
                    </div>
                    <!-- <div class="trade-details__code">
                        <h4 class="trade-details__code-heading">Code</h4>
                        <div class="trade-details__code-field form-group">
                            <div class="form-group__field-group"><input class="form-group__field" name="unfilled" value="{{ item.proof_opened }}" disabled></div>
                        </div><span class="trade-details__code-caption">Opened by Vendor</span>
                    </div> -->
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

cadmin/templates/cadmin/trades.html
{% extends 'cadmin/base-site.html' %}
{% load i18n %}
{% load static %}

{% block title %}Trades{% endblock %}

{% block page-inner %}
<main class="page__inner js-nav-close-trigger trades">
    <section class="section">
        <header class="section__header">
            <nav class="section__nav page-nav">
                <a class="page-nav__item {%if status == ''%}is-active{%endif%}" href="{{ cadmin_url }}/trades?start_date={{ start_date }}&end_date={{ end_date }}&search={{ search }}">All ({{ count|keyvalue:"all" }})</a>
                <a class="page-nav__item {%if status == 'waiting'%}is-active{%endif%}" href="{{ cadmin_url }}/trades?start_date={{ start_date }}&end_date={{ end_date }}&search={{ search }}&status=Waiting+for+trade+intiator">Waiting for trade intiator ({{ count|keyvalue:"waiting" }})</a>
                <a class="page-nav__item {%if status == 'archived'%}is-active{%endif%}" href="{{ cadmin_url }}/trades?start_date={{ start_date }}&end_date={{ end_date }}&search={{ search }}&status=Archive">Archive ({{ count|keyvalue:"archived" }})</a>
                <a class="page-nav__item {%if status == 'completed'%}is-active{%endif%}" href="{{ cadmin_url }}/trades?start_date={{ start_date }}&end_date={{ end_date }}&search={{ search }}&status=Completed">Completed ({{ count|keyvalue:"completed" }})</a>
            </nav>
        </header>
        <div class="section__inner">
            <form class="date-filter" style="margin-bottom: 20px;" action="" method="GET">
                <div class="date-filter__inputs">
                    <div class="date-filter__field form-group">
                        <div class="form-group__field-group"><svg class="form-group__calendar" width="30">
                                <use xlink:href="{% static 'cadmin/images/icons.svg' %}#calendar-alt"></use>
                            </svg><input class="form-group__field js-datepicker-toggle" name="start_date" placeholder="7 Nov 2019" value="{{ start_date }}" readonly required></div>
                    </div>
                    <div class="date-filter__divider">to</div>
                    <div class="date-filter__field form-group">
                        <div class="form-group__field-group"><svg class="form-group__calendar" width="30">
                                <use xlink:href="{% static 'cadmin/images/icons.svg' %}#calendar-alt"></use>
                            </svg><input class="form-group__field js-datepicker-toggle" name="end_date" placeholder="12 Nov 2019" value="{{ end_date }}" readonly required></div>
                    </div><button class="date-filter__apply btn btn--red" type="submit">Apply filter</button>
                </div>
                <div class="section__search form-group search">
                    <div class="form-group__field-group"><input class="form-group__field" name="search" value="{{ search }}" placeholder="Search in Trades"><button class="search__btn" type="submit">Search</button></div>
                </div>
            </form>
            <table class="section__table table table--large">
                <thead>
                    <tr>
                        <th>Trade ID</th>
                        <th>Offer ID</th>
                        <th>Trade initiator</th>
                        <th>Vendor</th>
                        <th>Payment method</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td><span class="table__mobile-heading">Trade ID</span><a href="#">{{ item.id }}</a></td>
                        <td><span class="table__mobile-heading">Offer ID</span><a href="{{ cadmin_url }}/offer-details?item_id={{ item.offer.id }}">{{ item.offer.id }}</a></td>
                        <td><span class="table__mobile-heading">Trade initiator</span><a href="#">{{ item.trade_initiator|default_if_none:"" }}</a></td>
                        <td><span class="table__mobile-heading">Vendor</span><a href="#">{{ item.vendor }}</a></td>
                        <td><span class="table__mobile-heading">Payment method</span><span>{{ item.payment_method }}</span></td>
                        <td><span class="table__mobile-heading">Amount</span><span>{{ item.amount }} {{ item.offer.what_crypto }}</span></td>
                        <td><span class="table__mobile-heading">Status</span><span>{{ item.get_status_display }}</span></td>
                        <td><span class="table__mobile-heading">Status</span><span>[[?]]</span></td>
                        <td><span class="table__mobile-heading">Actions</span><a href="{{ cadmin_url }}/trade-details?item_id={{ item.id }}">Details</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <nav class="section__pagination pagination">
                <ul class="pagination__list">
                    {% if items.has_previous %}
                    <li class="pagination__item"><a href="{{ base_url }}page={{ items.previous_page_number }}" rel="first">Prev</a></li>
                    {% else %}
                    <li class="pagination__item disabled">Prev</li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                         {% if items.number == i %}
                         <li class="pagination__item is-active"><a href="{{ base_url }}page={{ i }}">{{ i }}</a></li>
                         {% else %}
                         <li class="pagination__item"><a href="{{ base_url }}page={{ i }}">{{ i }}</a></li>
                         {% endif %}
                    {% endfor %}
                    {% if items.has_next %}
                    <li class="pagination__item"><a href="{{ base_url }}page={{ items.next_page_number }}" rel="next">Next</a></li>
                    {% else %}
                    <li class="pagination__item disabled">Next</li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </section>
</main>
{% endblock %}